spec:
  name: expense-tracker
  static_sites:
    - name: client
      source_dir: client
      github:
        branch: main
        deploy_on_push: true
      build_command: npm ci && npm run build
      output_dir: dist
      index_document: index.html
      error_document: index.html
      routes:
        - path: /
      envs:
        - key: VITE_API_URL
          value: "/api"
          scope: RUN_AND_BUILD_TIME
  services:
    - name: server
      source_dir: server
      github:
        branch: main
        deploy_on_push: true
      build_command: npm ci
      run_command: npm start
      http_port: 5000
      routes:
        - path: /api
      envs:
        - key: PORT
          value: "5000"
          scope: RUN_TIME
        - key: MONGO_URI
          value: ""
          scope: RUN_TIME
        - key: JWT_SECRET
          value: ""
          scope: RUN_TIME
        - key: CORS_ORIGIN
          value: "https://walrus-app-s4zqu.ondigitalocean.app"
          scope: RUN_TIME
